// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/cs2/internal/workers/parser.go

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/cs2/internal/parser/types"
)

// MockGameParser is a mock of GameParser interface.
type MockGameParser struct {
	ctrl     *gomock.Controller
	recorder *MockGameParserMockRecorder
}

// MockGameParserMockRecorder is the mock recorder for MockGameParser.
type MockGameParserMockRecorder struct {
	mock *MockGameParser
}

// NewMockGameParser creates a new mock instance.
func NewMockGameParser(ctrl *gomock.Controller) *MockGameParser {
	mock := &MockGameParser{ctrl: ctrl}
	mock.recorder = &MockGameParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameParser) EXPECT() *MockGameParserMockRecorder {
	return m.recorder
}

// Next mocks base method.
func (m *MockGameParser) Next(ctx context.Context) (*types.GameParser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(*types.GameParser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockGameParserMockRecorder) Next(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockGameParser)(nil).Next), ctx)
}

// MockGameSaver is a mock of GameSaver interface.
type MockGameSaver struct {
	ctrl     *gomock.Controller
	recorder *MockGameSaverMockRecorder
}

// MockGameSaverMockRecorder is the mock recorder for MockGameSaver.
type MockGameSaverMockRecorder struct {
	mock *MockGameSaver
}

// NewMockGameSaver creates a new mock instance.
func NewMockGameSaver(ctrl *gomock.Controller) *MockGameSaver {
	mock := &MockGameSaver{ctrl: ctrl}
	mock.recorder = &MockGameSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameSaver) EXPECT() *MockGameSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockGameSaver) Save(ctx context.Context, games []types.GameDB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, games)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGameSaverMockRecorder) Save(ctx, games interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGameSaver)(nil).Save), ctx, games)
}
