// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/cs2/internal/traintestsplitter/workers/train_test_splitter.go

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/cs2/internal/traintestsplitter/types"
)

// MockTrainTestSplitGetter is a mock of TrainTestSplitGetter interface.
type MockTrainTestSplitGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTrainTestSplitGetterMockRecorder
}

// MockTrainTestSplitGetterMockRecorder is the mock recorder for MockTrainTestSplitGetter.
type MockTrainTestSplitGetterMockRecorder struct {
	mock *MockTrainTestSplitGetter
}

// NewMockTrainTestSplitGetter creates a new mock instance.
func NewMockTrainTestSplitGetter(ctrl *gomock.Controller) *MockTrainTestSplitGetter {
	mock := &MockTrainTestSplitGetter{ctrl: ctrl}
	mock.recorder = &MockTrainTestSplitGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainTestSplitGetter) EXPECT() *MockTrainTestSplitGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTrainTestSplitGetter) Get(ctx context.Context) (*types.TrainTestSplit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*types.TrainTestSplit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTrainTestSplitGetterMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTrainTestSplitGetter)(nil).Get), ctx)
}

// MockTrainTestSplitSaver is a mock of TrainTestSplitSaver interface.
type MockTrainTestSplitSaver struct {
	ctrl     *gomock.Controller
	recorder *MockTrainTestSplitSaverMockRecorder
}

// MockTrainTestSplitSaverMockRecorder is the mock recorder for MockTrainTestSplitSaver.
type MockTrainTestSplitSaverMockRecorder struct {
	mock *MockTrainTestSplitSaver
}

// NewMockTrainTestSplitSaver creates a new mock instance.
func NewMockTrainTestSplitSaver(ctrl *gomock.Controller) *MockTrainTestSplitSaver {
	mock := &MockTrainTestSplitSaver{ctrl: ctrl}
	mock.recorder = &MockTrainTestSplitSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainTestSplitSaver) EXPECT() *MockTrainTestSplitSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockTrainTestSplitSaver) Save(ctx context.Context, split types.TrainTestSplit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, split)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTrainTestSplitSaverMockRecorder) Save(ctx, split interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTrainTestSplitSaver)(nil).Save), ctx, split)
}
